name: Deploy to DO

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DO
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            cd github_pages_api
            git pull
            npm install
            pm2 delete index
            pm2 start index.js -- secrets.NODEMAIL_EMAIL secrets.NODEMAIL_PASSWORD
            sudo systemctl reload nginx
