name: Deploy to DO

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DO
        uses: appleboy/ssh-action@v0.1.2
        env:
          FOO: "bar"
          NODEMAIL_EMAIL: ${{secrets.NODEMAIL_EMAIL}}
          NODEMAIL_PASSWORD: ${{secrets.NODEMAIL_PASSWORD}}
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          envs: NODEMAIL_EMAIL,NODEMAIL_PASSWORD

          script: |
            cd github_pages_api
            git pull
            npm install
            pm2 delete index
            pm2 start index.js -- $NODEMAIL_EMAIL $NODEMAIL_PASSWORD
            sudo systemctl reload nginx
